apiVersion: v1
kind: Service
metadata:
  name: fastapi-prediction-app
spec:
  selector:
    app: fastapi-prediction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer